#!/bin/bash

CURRENT_TIME=$(date "+%Y.%m.%d-%H.%M.%S")

npx hardhat clean

mapfile -t OUTPUT < <(npx hardhat run scripts/deploy.js --network kovan)

CONTRACT_ADDRESS=($"${OUTPUT[2]}")
DEPLOYER_ADDRESS=($"${OUTPUT[3]}")
SET_BYTES32_VAL=($"${OUTPUT[4]}")
BYTES32_TX=($"${OUTPUT[5]}")
GET_BYTES32_TX=($"${OUTPUT[6]}")

echo "$CONTRACT_ADDRESS"
echo "$DEPLOYER_ADDRESS"
echo "$SET_BYTES32_VAL"
echo "$GET_BYTES32_TX"
echo "$BYTES32_TX"

echo "{\"contract_address\":\"${CONTRACT_ADDRESS: -42:42}\", \
\"deployer_address\":\"${DEPLOYER_ADDRESS: -42:42}\", \
\"set_bytes32_value\":\"${SET_BYTES32_VAL: -66:66}\", \
\"get_bytes32_value\":\"${GET_BYTES32_TX: -66:66}\", \
\"bytes32_tx\":\"${BYTES32_TX: -66:66}\"}" > contract_data_$CURRENT_TIME.json
